/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API root */
        get: operations["readRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/year/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single year
         * @description Returns a single Year object with game parameters and statistics for the specified year
         */
        get: operations["readYear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple years
         * @description Returns a list of Year objects since 2002. Supports filtering and sorting.
         *     Returns up to 1000 results at a time.
         */
        get: operations["readYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team/{team}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single team
         * @description Returns a single Team object with all-time statistics
         */
        get: operations["readTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple teams
         * @description Returns a list of Team objects with all-time statistics.
         *     Returns up to 1000 results at a time.
         */
        get: operations["readTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2002": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query team performance for 2002
         * @description Returns Team Year object for 2002 with EPA and statistics
         */
        get: operations["readTeamYear2002"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2003": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2003 */
        get: operations["readTeamYear2003"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2004": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2004 */
        get: operations["readTeamYear2004"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2005": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2005 */
        get: operations["readTeamYear2005"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2006": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2006 */
        get: operations["readTeamYear2006"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2007": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2007 */
        get: operations["readTeamYear2007"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2008": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2008 */
        get: operations["readTeamYear2008"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2009": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2009 */
        get: operations["readTeamYear2009"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2010": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2010 */
        get: operations["readTeamYear2010"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2011": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2011 */
        get: operations["readTeamYear2011"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2012": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2012 */
        get: operations["readTeamYear2012"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2013": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2013 */
        get: operations["readTeamYear2013"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2014": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2014 */
        get: operations["readTeamYear2014"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2015": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2015 */
        get: operations["readTeamYear2015"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2016": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query team performance for 2016
         * @description 2016 introduces EPA breakdowns by component (e.g., auto_epa, teleop_epa, etc.)
         */
        get: operations["readTeamYear2016"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2017": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2017 */
        get: operations["readTeamYear2017"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2018": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2018 */
        get: operations["readTeamYear2018"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2019": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2019 */
        get: operations["readTeamYear2019"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2020": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2020 */
        get: operations["readTeamYear2020"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2021": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2021 */
        get: operations["readTeamYear2021"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2022": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query team performance for 2022 */
        get: operations["readTeamYear2022"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2023": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query team performance for 2023
         * @description 2023 was the Charged Up game. Includes EPA breakdowns for auto, teleop, endgame,
         *     and game-specific components.
         */
        get: operations["readTeamYear2023"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2024": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query team performance for 2024
         * @description 2024 was the Crescendo game. Includes EPA breakdowns for auto, teleop, endgame,
         *     ranking points, and game-specific components.
         */
        get: operations["readTeamYear2024"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_year/{team}/2025": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query team performance for 2025
         * @description 2025 is the Reefscape game. Includes EPA breakdowns for auto, teleop, endgame,
         *     ranking points, and game-specific components.
         */
        get: operations["readTeamYear2025"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple team years
         * @description Returns a list of TeamYear objects with EPA and statistics.
         *     Returns up to 1000 results at a time.
         */
        get: operations["readTeamYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{event_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single event
         * @description Returns a single Event object with EPA statistics
         */
        get: operations["readEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple events
         * @description Returns a list of Event objects. Returns up to 1000 results at a time.
         */
        get: operations["readEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_event/{team}/{event_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single team's performance at an event
         * @description Returns a single TeamEvent object with EPA statistics
         */
        get: operations["readTeamEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple team event entries
         * @description Returns a list of TeamEvent objects. Returns up to 1000 results at a time.
         */
        get: operations["readTeamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/{match_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single match
         * @description Returns a single Match object with scores and EPA predictions
         */
        get: operations["readMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple matches
         * @description Returns a list of Match objects. Returns up to 1000 results at a time.
         */
        get: operations["readMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_match/{team}/{match_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single team's performance in a match
         * @description Returns a single TeamMatch object with team-specific match data
         */
        get: operations["readTeamMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team_matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple team match entries
         * @description Returns a list of TeamMatch objects. Returns up to 1000 results at a time.
         */
        get: operations["readTeamMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Win/loss/tie record and winrate */
        Record: {
            /** @description Number of wins */
            wins: number;
            /** @description Number of losses */
            losses: number;
            /** @description Number of ties */
            ties: number;
            /** @description Total number of matches */
            count: number;
            /**
             * Format: float
             * @description Win rate (0.0-1.0)
             */
            winrate: number;
        };
        /** @description EPA (Elo Performance Analysis) statistics */
        EPAStats: {
            /**
             * Format: float
             * @description EPA at season start
             */
            start?: number | null;
            /**
             * Format: float
             * @description EPA before championships
             */
            pre_champs?: number | null;
            /**
             * Format: float
             * @description Peak EPA during season
             */
            max?: number | null;
        };
        /** @description Ranking information with percentile */
        PercentileRank: {
            /** @description Absolute rank position */
            rank?: number | null;
            /**
             * Format: float
             * @description Percentile ranking (0.0-1.0)
             */
            percentile?: number | null;
            /** @description Total number of teams ranked */
            team_count?: number | null;
        };
        /** @description EPA rankings by region */
        EPARanks: {
            /** @description Global EPA ranking */
            total?: components["schemas"]["PercentileRank"];
            /** @description Country EPA ranking */
            country?: components["schemas"]["PercentileRank"];
            /** @description State EPA ranking */
            state?: components["schemas"]["PercentileRank"];
            /** @description District EPA ranking */
            district?: components["schemas"]["PercentileRank"];
        };
        /** @description FRC year with game parameters and statistics */
        Year: {
            /** @description Four-digit year */
            year: number;
            /**
             * Format: float
             * @description Mean match score
             */
            score_mean: number;
            /**
             * Format: float
             * @description Standard deviation of match scores
             */
            score_sd: number;
            /**
             * Format: float
             * @description Mean fouls per match
             */
            foul_mean?: number;
            /**
             * Format: float
             * @description Mean score without fouls
             */
            no_foul_mean?: number;
            /**
             * Format: float
             * @description Mean autonomous points per match
             */
            auto_mean?: number;
            /**
             * Format: float
             * @description Mean teleoperated points per match
             */
            teleop_mean?: number;
            /**
             * Format: float
             * @description Mean endgame points per match
             */
            endgame_mean?: number;
            /**
             * Format: float
             * @description Mean ranking point 1 value
             */
            rp_1_mean?: number;
            /**
             * Format: float
             * @description Mean ranking point 2 value
             */
            rp_2_mean?: number;
            /**
             * Format: float
             * @description Mean ranking point 3 value (2025+)
             */
            rp_3_mean?: number;
            /**
             * Format: float
             * @description Mean tiebreaker points
             */
            tiebreaker_mean?: number;
            /**
             * Format: float
             * @description Mean game-specific component 1
             */
            comp_1_mean?: number;
            /**
             * Format: float
             * @description Mean game-specific component 2
             */
            comp_2_mean?: number;
            /**
             * Format: float
             * @description 99th percentile EPA
             */
            epa_99p?: number | null;
            /**
             * Format: float
             * @description 90th percentile EPA
             */
            epa_90p?: number | null;
            /**
             * Format: float
             * @description 75th percentile EPA
             */
            epa_75p?: number | null;
            /**
             * Format: float
             * @description 25th percentile EPA
             */
            epa_25p?: number | null;
        };
        /** @description FRC team information with all-time statistics */
        Team: {
            /** @description Team number */
            team: number;
            /** @description Team name */
            name: string;
            /** @description Country where team is located */
            country?: string | null;
            /** @description State where team is located (US teams) */
            state?: string | null;
            /** @description District code if applicable */
            district?: string | null;
            /** @description Year team first competed */
            rookie_year?: number | null;
            /** @description Whether team competed in last year */
            active: boolean;
            /** @description All-time record */
            record: components["schemas"]["Record"];
            /** @description Normalized EPA statistics */
            norm_epa?: {
                /** Format: float */
                current?: number | null;
                /** Format: float */
                recent?: number | null;
                /** Format: float */
                mean?: number | null;
                /** Format: float */
                max?: number | null;
            };
        };
        /** @description Team's performance in a specific FRC year */
        TeamYear: {
            /** @description Team number */
            team: number;
            /** @description Competition year */
            year: number;
            /** @description Team name */
            name: string;
            country?: string | null;
            state?: string | null;
            district?: string | null;
            rookie_year?: number | null;
            /** @description Detailed EPA breakdown for the year */
            epa: {
                total_points?: {
                    /**
                     * Format: float
                     * @description Mean EPA
                     */
                    mean?: number;
                    /**
                     * Format: float
                     * @description Standard deviation
                     */
                    sd?: number;
                };
                /**
                 * Format: float
                 * @description Unitless EPA
                 */
                unitless?: number;
                /**
                 * Format: float
                 * @description Normalized EPA
                 */
                norm?: number | null;
                /** @description 95% confidence interval [lower, upper] */
                conf?: number[];
                /**
                 * @description EPA broken down by game components. Available for 2016+.
                 *     Includes auto_epa, teleop_epa, endgame_epa, and game-specific components.
                 */
                breakdown?: {
                    [key: string]: number | null;
                };
                stats?: components["schemas"]["EPAStats"];
                ranks?: components["schemas"]["EPARanks"];
            };
            record: components["schemas"]["Record"];
            district_points?: number | null;
            district_rank?: number | null;
            /** @description Available for current year only */
            competing?: {
                this_week?: boolean;
                next_event_key?: string | null;
                next_event_name?: string | null;
                next_event_week?: number | null;
            } | null;
        };
        /** @description FRC competition event */
        Event: {
            /** @description Event key (e.g., `2024ncwak`) */
            key: string;
            /** @description Year the event occurred */
            year: number;
            /** @description Event name */
            name: string;
            /** @description Unix timestamp */
            time: number;
            country?: string | null;
            state?: string | null;
            district?: string | null;
            /**
             * Format: date
             * @description Event start date (YYYY-MM-DD)
             */
            start_date?: string;
            /**
             * Format: date
             * @description Event end date (YYYY-MM-DD)
             */
            end_date?: string;
            /** @enum {string} */
            type: "regional" | "district" | "district_cmp" | "cmp_division" | "cmp_finals";
            /** @description Week number in season */
            week: number;
            /** @description Link to livestream */
            video?: string | null;
            /** @enum {string} */
            status: "Upcoming" | "Ongoing" | "Completed";
            /** @description Human-readable status string */
            status_str?: string;
            /** @description Number of teams competing */
            num_teams?: number;
            /** @description Current/last match number (-1 for upcoming) */
            current_match?: number | null;
            /** @description Total number of qualification matches */
            qual_matches?: number | null;
            /** @description EPA statistics for event */
            epa?: {
                /** Format: float */
                max?: number | null;
                /** Format: float */
                top_8?: number | null;
                /** Format: float */
                top_24?: number | null;
                /** Format: float */
                mean?: number | null;
                /** Format: float */
                sd?: number | null;
            };
            /** @description Model performance metrics */
            metrics?: {
                win_prob?: {
                    count?: number;
                    /** Format: float */
                    conf?: number | null;
                    /** Format: float */
                    acc?: number | null;
                    /** Format: float */
                    mse?: number | null;
                };
                score_pred?: {
                    count?: number;
                    /** Format: float */
                    rmse?: number | null;
                };
            };
        };
        /** @description A team's performance at a specific event */
        TeamEvent: {
            team: number;
            year: number;
            event_key: string;
            name: string;
            event_name?: string;
            event_week?: number;
            epa: {
                total_points?: {
                    /** Format: float */
                    mean?: number;
                    /** Format: float */
                    sd?: number;
                };
                breakdown?: {
                    [key: string]: number | null;
                };
            };
            record: components["schemas"]["Record"];
            ranking?: {
                rank?: number;
                rp?: number;
            } | null;
        };
        /** @description Alliance data for a match */
        MatchAlliance: {
            team_1?: number;
            team_2?: number;
            team_3?: number | null;
            /** @description Comma-separated list of disqualified team numbers */
            dqs?: string;
            /** @description Comma-separated list of surrogate team numbers */
            surrogates?: string;
            score?: number | null;
            auto?: number | null;
            teleop?: number | null;
            endgame?: number | null;
            no_foul?: number | null;
            foul?: number | null;
            rp_1?: boolean | null;
            rp_2?: boolean | null;
            /** @description Only for 2025+ */
            rp_3?: boolean | null;
            tiebreaker?: number | null;
            /** @description Game-specific component scores */
            components?: {
                [key: string]: number | null;
            };
            /** @description EPA predictions */
            epa_pred?: {
                /** Format: float */
                win_prob?: number | null;
                /** Format: float */
                score?: number | null;
                /** Format: float */
                rp_1?: number | null;
                /** Format: float */
                rp_2?: number | null;
                /** Format: float */
                rp_3?: number | null;
            };
        };
        /** @description A single FRC match with scores and results */
        Match: {
            /** @description Match key */
            key: string;
            year: number;
            event_key: string;
            week: number;
            /**
             * @description Competition level
             * @enum {string}
             */
            comp_level: "qm" | "ef" | "qf" | "sf" | "f";
            set_number: number;
            match_number: number;
            /** @description Whether this is an elimination match */
            elim: boolean;
            /** @description Unix timestamp */
            time?: number | null;
            predicted_time?: number | null;
            /** @enum {string} */
            status: "Scheduled" | "Unstarted" | "In Progress" | "Completed";
            video?: string | null;
            red: components["schemas"]["MatchAlliance"];
            blue: components["schemas"]["MatchAlliance"];
            /** @enum {string|null} */
            winner?: "Red" | "Blue" | "Tie" | null;
        };
        /** @description A team's performance in a specific match */
        TeamMatch: {
            team: number;
            year: number;
            event_key: string;
            match_key: string;
            /** @enum {string} */
            alliance: "Red" | "Blue";
            /** @description Alliance-relative match number (1, 2, or 3) */
            team_match_number?: number;
            /** @description Whether team was a surrogate or substitute */
            surrogacy?: string | null;
            /** @description Whether team was disqualified */
            dq?: boolean;
            /** @description EPA statistics */
            epa?: {
                total_points?: {
                    /** Format: float */
                    mean?: number;
                };
            };
            record?: components["schemas"]["Record"];
        };
        /** @description Error response */
        Error: {
            /** @description Error message */
            detail: string;
        };
        /** @description Validation error for invalid request parameters */
        ValidationError: {
            /** @description Location of the error (field path) */
            loc: (string | number)[];
            /** @description Error message */
            msg: string;
            /** @description Error type */
            type: string;
        };
        /** @description HTTP validation error response */
        HTTPValidationError: {
            /** @description List of validation errors */
            detail: components["schemas"]["ValidationError"][];
        };
    };
    responses: never;
    parameters: {
        /** @description Team number (no prefix, e.g., 5511) */
        TeamQuery: number;
        /** @description Four-digit year (e.g., 2023, 2024). Valid from 2002 onwards. */
        YearQuery: number;
        /** @description Capitalized country name (e.g., `USA`, `Canada`) */
        CountryQuery: string;
        /** @description Two-letter state code (e.g., `NC`, `CA`, `TX`) */
        StateQuery: string;
        /** @description District code */
        DistrictQuery: "fma" | "fnc" | "fsc" | "fit" | "fin" | "fim" | "ne" | "chs" | "ont" | "pnw" | "pch" | "isr";
        /** @description Whether the team has played in the last year */
        ActiveQuery: boolean;
        /** @description Event key (e.g., `2024ncwak`) */
        EventQuery: string;
        /** @description Week of competition (0-8, where 8 is Championship) */
        WeekQuery: number;
        /** @description Column name to sort by */
        MetricQuery: string;
        /** @description Sort in ascending order (default is descending) */
        AscendingQuery: boolean;
        /** @description Maximum number of results to return (1-1000, default 1000) */
        LimitQuery: number;
        /** @description Offset from first result */
        OffsetQuery: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
        };
    };
    readYear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Four-digit year (e.g., 2023, 2024) */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Year object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Year"];
                };
            };
            /** @description Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readYears: {
        parameters: {
            query?: {
                /** @description Column name to sort by */
                metric?: string;
                /** @description Sort in ascending order (default is descending) */
                ascending?: components["parameters"]["AscendingQuery"];
                /** @description Maximum number of results to return (1-1000, default 1000) */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Offset from first result */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Year objects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Year"][];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team number (no prefix, e.g., 5511) */
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description Team not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeams: {
        parameters: {
            query?: {
                /** @description Capitalized country name (e.g., `USA`, `Canada`) */
                country?: components["parameters"]["CountryQuery"];
                /** @description Two-letter state code (e.g., `NC`, `CA`, `TX`) */
                state?: components["parameters"]["StateQuery"];
                /** @description District code */
                district?: components["parameters"]["DistrictQuery"];
                /** @description Whether the team has played in the last year */
                active?: components["parameters"]["ActiveQuery"];
                /** @description Column name to sort by */
                metric?: components["parameters"]["MetricQuery"];
                /** @description Sort in ascending order (default is descending) */
                ascending?: components["parameters"]["AscendingQuery"];
                /** @description Maximum number of results to return (1-1000, default 1000) */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Offset from first result */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Team objects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2002: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team number (no prefix, e.g., 5511) */
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2003: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2004: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2005: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2006: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2007: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2008: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2009: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2010: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2011: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2012: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2013: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2014: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2015: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2016: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2017: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2018: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2019: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2020: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2021: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2022: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2023: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYear2024: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readTeamYear2025: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamYear object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"];
                };
            };
            /** @description Team Year not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamYears: {
        parameters: {
            query?: {
                /** @description Team number (no prefix, e.g., 5511) */
                team?: components["parameters"]["TeamQuery"];
                /** @description Four-digit year (e.g., 2023, 2024). Valid from 2002 onwards. */
                year?: components["parameters"]["YearQuery"];
                /** @description Capitalized country name (e.g., `USA`, `Canada`) */
                country?: components["parameters"]["CountryQuery"];
                /** @description Two-letter state code (e.g., `NC`, `CA`, `TX`) */
                state?: components["parameters"]["StateQuery"];
                /** @description District code */
                district?: components["parameters"]["DistrictQuery"];
                /** @description Column name to sort by */
                metric?: components["parameters"]["MetricQuery"];
                /** @description Sort in ascending order (default is descending) */
                ascending?: components["parameters"]["AscendingQuery"];
                /** @description Maximum number of results to return (1-1000, default 1000) */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Offset from first result */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of TeamYear objects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamYear"][];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event key (e.g., `2024ncwak`, `2023mihat`) */
                event_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readEvents: {
        parameters: {
            query?: {
                /** @description Four-digit year (e.g., 2023, 2024). Valid from 2002 onwards. */
                year?: components["parameters"]["YearQuery"];
                /** @description Capitalized country name (e.g., `USA`, `Canada`) */
                country?: components["parameters"]["CountryQuery"];
                /** @description Two-letter state code (e.g., `NC`, `CA`, `TX`) */
                state?: components["parameters"]["StateQuery"];
                /** @description District code */
                district?: components["parameters"]["DistrictQuery"];
                /** @description Event type */
                type?: "regional" | "district" | "district_cmp" | "cmp_division" | "cmp_finals";
                /** @description Week of competition (0-8, where 8 is Championship) */
                week?: components["parameters"]["WeekQuery"];
                /** @description Column name to sort by */
                metric?: components["parameters"]["MetricQuery"];
                /** @description Sort in ascending order (default is descending) */
                ascending?: components["parameters"]["AscendingQuery"];
                /** @description Maximum number of results to return (1-1000, default 1000) */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Offset from first result */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Event objects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team number (no prefix, e.g., 5511) */
                team: number;
                /** @description Event key (e.g., `2024ncwak`) */
                event_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamEvent object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamEvent"];
                };
            };
            /** @description Team Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamEvents: {
        parameters: {
            query?: {
                /** @description Team number (no prefix, e.g., 5511) */
                team?: components["parameters"]["TeamQuery"];
                /** @description Four-digit year (e.g., 2023, 2024). Valid from 2002 onwards. */
                year?: components["parameters"]["YearQuery"];
                /** @description Event key (e.g., `2024ncwak`) */
                event?: components["parameters"]["EventQuery"];
                /** @description Capitalized country name (e.g., `USA`, `Canada`) */
                country?: components["parameters"]["CountryQuery"];
                /** @description Two-letter state code (e.g., `NC`, `CA`, `TX`) */
                state?: components["parameters"]["StateQuery"];
                /** @description District code */
                district?: components["parameters"]["DistrictQuery"];
                /** @description Event type */
                type?: "regional" | "district" | "district_cmp" | "cmp_division" | "cmp_finals";
                /** @description Week of competition (0-8, where 8 is Championship) */
                week?: components["parameters"]["WeekQuery"];
                /** @description Column name to sort by */
                metric?: components["parameters"]["MetricQuery"];
                /** @description Sort in ascending order (default is descending) */
                ascending?: components["parameters"]["AscendingQuery"];
                /** @description Maximum number of results to return (1-1000, default 1000) */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Offset from first result */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of TeamEvent objects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamEvent"][];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Match key (e.g., `2024ncwak_f1m1`, `2024ncwak_qm1`) */
                match_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Match object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            /** @description Match not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readMatches: {
        parameters: {
            query?: {
                /** @description Team number (no prefix, e.g., 5511) */
                team?: components["parameters"]["TeamQuery"];
                /** @description Four-digit year (e.g., 2023, 2024). Valid from 2002 onwards. */
                year?: components["parameters"]["YearQuery"];
                /** @description Event key (e.g., `2024ncwak`) */
                event?: components["parameters"]["EventQuery"];
                /** @description Week of competition (0-8, where 8 is Championship) */
                week?: components["parameters"]["WeekQuery"];
                /** @description Whether the match is an elimination match */
                elim?: boolean;
                /** @description Column name to sort by */
                metric?: components["parameters"]["MetricQuery"];
                /** @description Sort in ascending order (default is descending) */
                ascending?: components["parameters"]["AscendingQuery"];
                /** @description Maximum number of results to return (1-1000, default 1000) */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Offset from first result */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Match objects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"][];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team number (no prefix, e.g., 5511) */
                team: number;
                /** @description Match key (e.g., `2024ncwak_f1m1`) */
                match_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TeamMatch object retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMatch"];
                };
            };
            /** @description Team Match not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTeamMatches: {
        parameters: {
            query?: {
                /** @description Team number (no prefix, e.g., 5511) */
                team?: components["parameters"]["TeamQuery"];
                /** @description Four-digit year (e.g., 2023, 2024). Valid from 2002 onwards. */
                year?: components["parameters"]["YearQuery"];
                /** @description Event key (e.g., `2024ncwak`) */
                event?: components["parameters"]["EventQuery"];
                /** @description Week of competition (0-8, where 8 is Championship) */
                week?: components["parameters"]["WeekQuery"];
                /** @description Match key (e.g., `2024ncwak_f1m1`) */
                match?: string;
                /** @description Whether the match is an elimination match */
                elim?: boolean;
                /** @description Column name to sort by */
                metric?: components["parameters"]["MetricQuery"];
                /** @description Sort in ascending order (default is descending) */
                ascending?: components["parameters"]["AscendingQuery"];
                /** @description Maximum number of results to return (1-1000, default 1000) */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Offset from first result */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of TeamMatch objects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMatch"][];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
